[server]
  host = "127.0.0.1"
  port = 3004
  # Use mode demo when running watcher locally.
  # Mode demo whitelists all tokens so that entity values get updated.
  mode = "prod"

  # Checkpointing state.
  checkpointing = true

  # Checkpoint interval in number of blocks.
  checkpointInterval = 2000

  # IPFS API address (can be taken from the output on running the IPFS daemon).
  # ipfsApiAddr = "/ip4/127.0.0.1/tcp/5001"

  # Max block range for which to return events in eventsInRange GQL query.
  # Use -1 for skipping check on block range.
  maxEventsBlockRange = 1000

[metrics]
  host = "127.0.0.1"
  port = 9004
    [metrics.gql]
    port = 9005

[database]
  type = "postgres"
  host = "localhost"
  port = 5432
  database = "uni-info-watcher"
  username = "postgres"
  password = "postgres"
  synchronize = true
  logging = false
  maxQueryExecutionTime = 100

[upstream]
  [upstream.ethServer]
    gqlApiEndpoint = "http://127.0.0.1:8082/graphql"
    rpcProviderEndpoint = "http://127.0.0.1:8081"

  [upstream.cache]
    name = "requests"
    enabled = false
    deleteOnStart = false

  [upstream.uniWatcher]
    gqlEndpoint = "http://127.0.0.1:3003/graphql"
    gqlSubscriptionEndpoint = "http://127.0.0.1:3003/graphql"

  [upstream.tokenWatcher]
    gqlEndpoint = "http://127.0.0.1:3001/graphql"
    gqlSubscriptionEndpoint = "http://127.0.0.1:3001/graphql"

[jobQueue]
  dbConnectionString = "postgres://postgres:postgres@localhost/uni-info-watcher-job-queue"
  maxCompletionLagInSecs = 300
  jobDelayInMilliSecs = 1000
  eventsInBatch = 50
  subgraphEventsOrder = true
  blockDelayInMilliSecs = 2000
  prefetchBlocksInMem = true
  prefetchBlockCount = 10
