[server]
  host = "127.0.0.1"
  port = 3002

[upstream]
  gqlEndpoint = "http://127.0.0.1:8083/graphql"
  gqlSubscriptionEndpoint = "http://127.0.0.1:5000/graphql"

  [upstream.cache]
    name = "requests"
    enabled = false
    deleteOnStart = false
